[project]
name = "for5672"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ariadne>=0.26.2",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "ifcopenshell>=0.8.3.post2",
    "networkx>=3.5",
    "pyglet<2",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
    "trimesh>=4.9.0",
]

[tool.pyright]
typeCheckingMode = "basic"
